-- Projects and memberships. Generated by drizzle-kit, then hand-edited to
-- order projects before memberships and to append the data steps at the end:
-- seed the tvhs project as id 1, backfill logs/checkins (the ADD COLUMN default
-- of 1 does that for existing rows), and enrol every existing user in tvhs.
CREATE TABLE `projects` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`code` text NOT NULL,
	`name` text NOT NULL,
	`timezone` text DEFAULT 'America/Chicago' NOT NULL,
	`settings` text DEFAULT '{}' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projects_code_unique` ON `projects` (`code`);--> statement-breakpoint
CREATE TABLE `memberships` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`project_id` integer NOT NULL,
	`role` text NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "memberships_role_check" CHECK("memberships"."role" IN ('admin','ops_manager','dispatcher','courier','client_viewer'))
);
--> statement-breakpoint
CREATE INDEX `memberships_project_id_idx` ON `memberships` (`project_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `memberships_user_project_unique` ON `memberships` (`user_id`,`project_id`);--> statement-breakpoint
INSERT INTO `projects` (`id`, `code`, `name`, `timezone`, `settings`) VALUES (1, 'tvhs', 'TVHS RMD Courier', 'America/Chicago', '{}');--> statement-breakpoint
ALTER TABLE `checkins` ADD `project_id` integer DEFAULT 1 NOT NULL;--> statement-breakpoint
CREATE INDEX `checkins_project_id_idx` ON `checkins` (`project_id`);--> statement-breakpoint
ALTER TABLE `logs` ADD `project_id` integer DEFAULT 1 NOT NULL;--> statement-breakpoint
CREATE INDEX `logs_project_id_idx` ON `logs` (`project_id`);--> statement-breakpoint
INSERT INTO `memberships` (`user_id`, `project_id`, `role`)
	SELECT `id`, 1, CASE `role` WHEN 'admin' THEN 'admin' ELSE 'courier' END FROM `users`;
